
name: mobile-ci.yml

on:
  pull_request:
    branches: [feature]

jobs:
  build-android:
    name: Build Android App
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Android SDK
        uses: actions/setup-java@v2
        with:
          java-version: "11.x"
      - name: Setup Gradle
        uses: actions/setup-gradle@v1
      - name: Build Android App
        run: ./gradlew assembleDebug
      - name: Archive APK
        uses: actions/upload-artifact@v2
        with:
          name: android-app
          path: app/build/outputs/apk/debug/app-debug.apk

  build-ios:
    name: Build iOS App
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Xcode
        uses: actions/setup-xcode@v2
        with:
          xcode-version: "12.x"
      - name: Install CocoaPods Dependencies
        run: pod install
