
name: docker-build-and-test.yml

on:
  push:
    branches: [ develop ]
    
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build -t my-app:latest .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push my-app:latest
      - name: Install dependencies
        run: |
          docker pull node:16-alpine
          docker run --rm -v $(pwd):/app -w /app node:16-alpine npm install
          docker run --rm -v $(pwd):/app -w /app node:16-alpine npm run build
          docker pull python:3.9
          docker run --rm -v $(pwd):/app -w /app python:3.9 pip install -r requirements.txt
          docker run --rm -v $(pwd):/app -w /app python:3.9 python manage.py collectstatic --no-input
  run-integration-tests:
    runs-on: ubuntu-latest