

name: mobile-ci.yml

on:
  pull_request:
    branches: [feature]

jobs:
  build-android:
    runs-on: macOS
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download gradle
        run: wget https://services.gradle.org/distributions/gradle-6.7-bin.zip
      - name: Unzip gradle
        run: unzip -qq gradle-6.7-bin.zip
      - name: Setup gradle environment
        run: echo "export PATH=$PATH:/home/runner/work/_temp/_github_home/gradle-6.7/bin" >> $HOME/.bash_profile
      - name: Build Android app
        run: ./gradlew assembleDebug
      - name: Archive APK file
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

  build-ios:
    runs-on: macOS
    steps:
      - uses: actions/checkout