

# branch-protection.yml

name: Branch Protection Workflow

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Check for code changes
        run: |
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
          if [ $? -eq 0 ]; then
            echo "Code changes detected."
          else
            echo "No code changes found."
            exit 1
          fi
      - name: Verify code coverage report
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report
          path: coverage/
      - name: Verify code linting and tests
        uses: actions/download-artifact@v2
        with:
          name: linting-and-tests
          path: linting-and-tests/
      - name: Fail workflow if requirements not met
        run: |
          if [ -d "coverage/" ] && [ -d "linting-and-tests/" ]; then
            echo "All requirements met."
          else