

name: branch-protection

on:
  push:
    branches: 
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: check if commit includes code changes
        uses: actions/github-script@v3
        with:
          script: |
            if (context.payload.commits.length === 0) {
              core.warning('Commit does not include any code changes. Workflow will be skipped.');
              process.exit(1);
            }
      
      - name: checkout code
        uses: actions/checkout@v2
      
      - name: Build using Gradle (if java code)
        if: ${{ contains(github.event.head_commit.modified, 'gradle') }}
        run: gradle build
      
      - name: Ensure code coverage report is available as artifact
        if: ${{ contains(github.event.head_commit.modified, 'gradle') }}
        run: gradle jacocoTestReport && mkdir coverage && mv build/reports/jacoco/test/jacocoTestReport.xml coverage/
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage/
      
      - name: Code lint