


name: branch-protection.yml

on:
  push:
    branches: 
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check for code changes
        uses: actions/github-script@v3
        with:
          script: |
            if (github.event.commits.length > 0) {
              console.log("Code changes detected");
            } else {
              console.log("No code changes detected, skipping branch rules enforcement.");
              return;
            }

      - name: Check for code coverage report
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report
        if: always()

      - name: Verify code linting and unit tests
        uses: actions/download-artifact@v2
        with:
          name: linting-unit-tests
        if: always()

      - name: Fail if requirements not met
        if: ${{ failure() }}
        run: exit 1