

ci.yml:

name: ci

on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        python-version: [3.7]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Lint code
        run: eslint .
      - name: Run tests
        run: npm test
      - name: Fail if errors or failures
        run: exit 1

  coverage-report:
    runs-on: ubuntu-latest
    steps:
      - name: Install additional dependencies
        run: npm install nyc
      - name: Generate coverage report
        run: nyc report --reporter=lcov
      - name: Upload report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./coverage/lcov.info